version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "06:00"
    timezone: America/New_York
  assignees:
  - "samsmithnz"
