name: 'DORA deployment frequency'
description: 'A GitHub Action to roughly calculate DORA deployment frequency'
inputs:
  workflows: # required. string array of the name of the workflows to process
    description: the workflow name that is being scanned. Separate multiple workflows with commas
    required: true
  owner-repo: # optional, defaults to current owner/repo
    description: target org/repo or owner/repo to run the calculation on
    required: true
    default: "${{ github.repository }}"
  default-branch:  # optional, defaults to main
    description: branch that is deploying to production
    required: true
    default: 'main'
  number-of-days: # optional, defaults to 30
    description: number of days to scan
    required: true
    default: "30"
  pat-token: # optional, defaults to an empty string ("")
    description: GitHub PAT Token
    default: ""
  actions-token: # optional, defaults to an empty string ("")
    description: GitHub Actions Token, commonly passed in as a variable (secrets.GITHUB_TOKEN)
    default: ""
  app-id:
    description: 'application id of the registered GitHub app'
    default: ""
  app-install-id:
    description: 'id of the installed instance of the GitHub app'
    default: ""
  app-private-key:
    description: 'private key which has been generated for the installed instance of the GitHub app'
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run DORA deployment frequency 
      shell: pwsh
      run: |
         $result = ${{ github.action_path }}/src/deploymentfrequency.ps1 -ownerRepo "${{ inputs.owner-repo }}" -workflows "${{ inputs.workflows }}" -branch "${{ inputs.default-branch }}" -numberOfDays ${{ inputs.number-of-days }} -patToken "${{ inputs.pat-token }}" -actionsToken "${{ inputs.actions-token }}" -appId "${{ inputs.app-id }}" -appInstallationId "${{ inputs.app-install-id }}" -appPrivateKey "${{ inputs.app-private-key }}"
         Write-Host "::set-output name=result::$result"
         Write-Output $result >> $env:GITHUB_STEP_SUMMARY
         
        
