name: 'DORA deployment frequency'
description: 'A GitHub Action to roughly calculate DORA deployment frequency'
inputs:
  workflows: # required. string array of the name of the workflows to process
    description: 'the workflow name that is being scanned. Separate multiple workflows with commas'
    required: true
  #- Org/Owner: will use environment variables
  #- Repo: will use environment variables 
  default-branch:  # optional, defaults to main
    description: 'branch that is deploying to production'
    required: true
    default: 'main'
  number-of-days: # optional, defaults to 30
    description: number of days to scan
    required: true
    default: 30
runs:
  using: "composite"
  steps:
    - name: Run DORA deployment frequency 
      shell: pwsh
      run: |
        $ownerRepo = "${{ github.repository }}" -split '/'
        $workflowsArray = $inputs.workflows -split ','
        echo "Hello $ownerRepo[0] - $ownerRepo[1]."
        echo "Hello $workflowsArray[0] (length: $workflowsArray.Length)."
        echo "Hello ${{ inputs.default-branch }}."
        echo "Hello ${{ inputs.number-of-days }}."
     
