name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test this repo
        uses: samsmithnz/deployment-frequency@main
        with:
          workflows: 'CI'
      - name: Test another repo
        uses: samsmithnz/deployment-frequency@main
        with:
          workflows: 'CI/CD'
          owner-repo: 'samsmithnz/DevOpsMetrics'
      - name: Test no workflow
        uses: samsmithnz/deployment-frequency@main
        with:
          workflows: ''
          owner-repo: 'samsmithnz/GitHubToAzureDevOps'
      - name: Test elite repo
        uses: samsmithnz/deployment-frequency@main
        with:
          workflows: 'Feature Flags CI/CD'
          owner-repo: 'samsmithnz/SamsFeatureFlags'
          
