name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test this repo
        uses: samsmithnz/deployment-frequency@MovingPSToNewFile
        with:
          workflows: 'CI'
      - name: Test another repo with all arguments
        uses: samsmithnz/deployment-frequency@main
        if: 0 == 1
        with:
          workflows: 'CI/CD'
          owner-repo: 'samsmithnz/DevOpsMetrics'
          default-branch: 'main'
          number-of-days: 30
      - name: Test no workflow
        uses: samsmithnz/deployment-frequency@main
        if: 0 == 1
        with:
          workflows: ''
          owner-repo: 'samsmithnz/GitHubToAzureDevOps'
      - name: Test elite repo
        uses: samsmithnz/deployment-frequency@main
        if: 0 == 1
        with:
          workflows: 'Feature Flags CI/CD'
          owner-repo: 'samsmithnz/SamsFeatureFlags'
          
